version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: