name: backend-deploy

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest
permissions:
id-token: write
contents: read

steps:
  - uses: actions/checkout@v4

  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 8.0.x

  - name: Restore
    run: dotnet restore
    working-directory: backend

  - name: Build
    run: dotnet build --configuration Release
    working-directory: backend

  - name: Publish
    run: dotnet publish --configuration Release --output publish
    working-directory: backend

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: app
      path: backend/publish

deploy:
runs-on: ubuntu-latest
needs: build
permissions:
id-token: write
contents: read

steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: app

  - name: Azure Login
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48DD34783CE3405EB25AB2F51992A43A }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20A9FA496B4B4607A371D6D770D8E656 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EF3FB6FFE61480CA2F5931C61983292 }}

  - name: Deploy to Azure
    uses: azure/webapps-deploy@v3
    with:
      app-name: cloud-app-backend-wiktoria
      package: .
