name: Build and deploy ASP.Net Core app to Azure Web App - cloud-app-backend-wiktoria

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: windows-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Set up .NET Core
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '8.x'

  - name: Restore
    run: dotnet restore
    working-directory: backend

  - name: Build
    run: dotnet build --configuration Release
    working-directory: backend

  - name: Publish
    run: dotnet publish -c Release -o publish
    working-directory: backend

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: backend-app
      path: backend/publish
```

deploy:
runs-on: windows-latest
needs: build

```
steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: backend-app

  - name: Login to Azure
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48DD34783CE3405EB25AB2F51992A43A }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20A9FA496B4B4607A371D6D770D8E656 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EF3FB6FFE61480CA2F5931C61983292 }}

  - name: Deploy
    uses: azure/webapps-deploy@v3
    with:
      app-name: 'cloud-app-backend-wiktoria'
      package: .
```
